### ISSUE TITLE
Implement get api

### ISSUE THREAD

**Issue by Jonxslays** [Jonxslays/unkey_sdk#3]
Implement the [Get API](https://docs.unkey.dev/api-reference/apis/get) endpoint.

# Acceptance Criteria

- Documented
- Example code

## Models

- `struct GetApiRequest`
    
- `struct GetApiResponse`

## ApiService

This service has not been created yet, at time of making this issue. Should be very simple following the example of the `KeyService`.

```rs
pub async fn get_api(api_id: GetApiRequest) -> Wrapped<GetApiResponse> {}
```

## Client

Add the `ApiService` created above to the `Client` if it is not already.

```rs
pub async fn get_api(api_id: GetApiRequest) -> Wrapped<GetApiResponse> {}
```

**Comment by WilfredAlmeida** [comment]
I'll work on this

**Comment by Jonxslays** [comment]
Sweet, thanks. I found we can use the `#[serde(rename_all = "camelCase")]` macro for our models as well, you'll see it used around the project now. Go that route instead of just serde rename.

**Comment by WilfredAlmeida** [comment]
That's cool
