### ISSUE TITLE
`the ? operator cannot be applied to type Wrapped<()>`

### ISSUE THREAD

**Issue by IgnisDa** [Jonxslays/unkey_sdk#37]
### Please describe your feature request

It would be great if `std::ops::Try` is implemented for `Wrapped<()>`

**Comment by IgnisDa** [comment]
In fact, it would be great if it behaves like a rust `Result` so that I can perform those operations (`.unwrap()`, `.ok()`) on it.

**Comment by Jonxslays** [comment]
Thats a great point. I will look into this.

**Comment by Jonxslays** [comment]
As of `v0.4.0` the methods that previously returned a `Wrapped<T>` now return a `Result<T, HttpError>`. Thanks @IgnisDa for the suggestion, it feels much more idiomatic. This should solve the DX issues you were experiencing.
