### ISSUE TITLE
[feat] Please include `code` from api response while verifying a key

### ISSUE THREAD

**Issue by IgnisDa** [Jonxslays/unkey_sdk#40]
### Please describe your feature request

https://docs.rs/unkey/latest/unkey/models/struct.VerifyKeyResponse.html

The response does not include why the key is not valid. It is part of the response of the API request: https://www.unkey.com/docs/api-reference/keys/verify.

**Comment by Jonxslays** [comment]
Hi, sorry for the delay. i will investigate this week.

**Comment by Jonxslays** [comment]
This is available as of v.0.5.0. Thanks for the request.
